version: 2
jobs:
  build:

    working_directory: ~/aismessages

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:

    - checkout

    - restore_cache:
        key: aismessages-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline # gets the project dependencies

    - save_cache:
        paths:
        - ~/.m2
        key: aismessages-{{ checksum "pom.xml" }}

    - run: mvn package # compile + test

    - store_test_results:
        path: target/surefire-reports

    - run:
        name: "Publish artifact for fork branch"
        command: |
          if [ "${CIRCLE_BRANCH}" == "dbs_fork" ]; then
            mvn deploy
          fi